import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from './components/Login'
import mcs from '../images/mcs.jpg'
import Footer from './components/Footer'
import App from './components/App'
import Header from './components/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learning Platform</title>
        <meta name="mcs" content="Generated by create next app" />
        <link rel="icon" href="/mcs.jpg" />
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.3/dist/flowbite.min.css" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">...</a>
        </h1>

        <div className={styles.grid}>
          <Login />
        </div>
      </main>

      <Footer />
      <script src="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js"></script>
    </div>
  )
}
