import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from './components/Login'
import mcs from '../images/mcs.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learning Platform</title>
        <meta name="mcs" content="Generated by create next app" />
        <link rel="icon" href="/mcs.jpg" />
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.3/dist/flowbite.min.css" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">...</a>
        </h1>

        <div className={styles.grid}>
          <Login />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://mcs.mn/mn/"
          target="_blank"
          rel="noopener noreferrer"
          className='font-semibold'
        >
          Learning Platform{' '}
          <span className={`${styles.logo} flex items-center`}>
          <Image
            src={mcs}
            width={120}
            height={50}
          />
          </span>
        </a>
      </footer>
      <script src="https://unpkg.com/@themesberg/flowbite@latest/dist/flowbite.bundle.js"></script>
    </div>
  )
}
